=== biggstd/ChemMD/src/chemmd/chemmd_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
      "node_information": {
        "type": "object",
        "properties": {
          "node_title": {
            "type": "string"
          },
          "node_description": {
            "type": "string"
          },
          "node_url": {
            "type": "string",
            "format": "uri"
          },
          "submission_date": {
            "type": "string",
            "format": "date-time"
          },
          "public_release_date": {
            "type": "string",
            "format": "date-time"
          }
        },
        "required": [
          "node_title",
          "node_url"
        ]
      },
      "factor": {
        "type": "object",
        "properties": {
          "factor_type": {
            "type": "string"
          },
          "decimal_value": {
            "type": "number"
          },
          "string_value": {
            "type": "string"
          },
          "reference_value": {
            "type": "string"
          },
          "unit_reference": {
            "type": "string"
          },
          "csv_column_index": {
            "type": "integer"
          }
        },
        "required": [
          "factor_type"
        ]
      },
      "factor_array": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/factor"
        }
      },
      "species": {
        "type": "object",
        "properties": {
          "species_reference": {
            "type": "string"
          },
          "stoichiometry": {
            "type": "number"
          }
        },
        "required": [
          "species_reference"
        ]
      },
      "species_array": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/species"
        }
      },
      "comment": {
        "type": "object",
        "properties": {
          "comment_title": {
            "type": "string"
          },
          "comment_body": {
            "type": "string"
          }
        },
        "required": [
          "comment_title",
          "comment_body"
        ]
      },
      "comment_array": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/comment"
        }
      },
      "source": {
        "type": "object",
        "properties": {
          "source_name": {
            "type": "string"
          },
          "source_factors": {
            "$ref": "#/definitions/factor_array"
          },
          "source_species": {
            "$ref": "#/definitions/species_array"
          },
          "source_comments": {
            "$ref": "#/definitions/comment_array"
          }
        }
      },
      "source_array": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/source"
        }
      },
      "sample": {
        "type": "object",
        "properties": {
          "sample_name": {
            "type": "string"
          },
          "sample_factors": {
            "$ref": "#/definitions/factor_array"
          },
          "sample_species": {
            "$ref": "#/definitions/species_array"
          },
          "sample_comments": {
            "$ref": "#/definitions/comment_array"
          },
          "sample_sources": {
            "$ref": "#/definitions/source_array"
          }
        }
      },
      "sample_array": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/sample"
        }
      },
      "experiment": {
        "type": "object",
        "properties": {
          "experiment_name": {
            "type": "string"
          },
          "experiment_comments": {
            "$ref": "#/definitions/comment_array"
          },
          "experiment_factors": {
            "$ref": "#/definitions/factor_array"
          },
          "experiment_samples": {
            "$ref": "#/definitions/sample_array"
          },
          "experiment_datafile": {
            "type": "string"
          }
        }
      },
      "experiment_array": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/experiment"
        }
      }
    },
    "type": "object",
    "title": "node",
    "properties": {
      "node_information": {
        "$ref": "#/definitions/node_information"
      },
      "node_comments": {
        "$ref": "#/definitions/comment_array"
      },
      "node_factors": {
        "$ref": "#/definitions/factor_array"
      },
      "node_experiments": {
        "$ref": "#/definitions/experiment_array"
      },
      "node_samples": {
        "$ref": "#/definitions/sample_array"
      }
    },
    "required": [
      "node_information",
      "node_experiments"
    ]
  }

=== biggstd/ChemMD/src/chemmd/demos/demo_json/sipos_2006_nmr_1.json
{
    "node_information": {
      "node_title": "Sipos 2006, Talanta NMR Figures",
      "node_description": "Extracted figures.",
      "node_url": "www.url.com",
      "submission_date": "2018-5-25",
      "public_release_date": "2006-03-13"
    },
    "node_comments": [
      {
        "comment_title": "Study level comment on Sipos 2006.",
        "comment_body": "I manually pulled this points out with a web tool."
      }
    ],
    "node_factors": [
      {
        "factor_type": "Measurement Condition",
        "decimal_value": 25.0,
        "unit_reference": "Celsius"
      },
      {
        "factor_type": "Measurement",
        "unit_reference": "ppm",
        "reference_value": "27_Al",
        "csv_column_index": 1
      },
      {
        "factor_type": "Measurement Condition",
        "decimal_value": 78.204,
        "reference_value": "27_Al",
        "unit_reference": "MHz"
      },
      {
        "factor_type": "Measurement Reference",
        "unit_reference": "27_Al Reference Compound",
        "reference_value": "[KAl(SO4)2]"
      }
    ],
    "node_experiments": [
      {
        "experiment_name": "Potassium Hydroxide Assay",
        "experiment_datafile": "sipos_2006_fig3_KOH.csv",
        "experiment_samples": [
          {
            "sample_name": "Potassium Hydroxide",
            "sample_factors": [
              {
                "factor_type": "Measurement Condition",
                "unit_reference": "Molar",
                "csv_column_index": 0
              }
            ],
            "sample_species": [
              {
                "species_reference": "K+",
                "stoichiometry": 1.0
              },
              {
                "species_reference": "OH-",
                "stoichiometry": 1.0
              }
            ]
          },
          {
            "sample_name": "Aluminate Solution",
            "sample_factors": [
              {
                "factor_type": "Measurement Condition",
                "decimal_value": 0.005,
                "unit_reference": "Molar"
              },
              {
                "factor_type": "Measurement",
                "unit_reference": "ppm",
                "reference_value": "27_Al",
                "csv_column_index": 1
              }
            ],
            "sample_species": [
              {
                "species_reference": "Al(III)",
                "stoichiometry": 1.0
              }
            ],
            "sample_sources": [
              {
                "sample_name": "Aluminum Wire",
                "source_factors": [
                  {
                    "factor_type": "Material Property",
                    "decimal_value": 0.98,
                    "unit_reference": "Percent",
                    "reference_value": "Purity by Weight"
                  }
                ],
                "source_species": [
                  {
                    "species_reference": "Al(III)",
                    "stoichiometry": 1.0
                  }
                ]
              }
            ]
          }
        ],
        "experiment_comments": [
          {
            "comment_title": "Data extraction method.",
            "comment_body": "I manually pulled this points out with a web tool."
          }
        ]
      },
      {
        "experiment_name": "Lithium Hydroxide Assay",
        "experiment_datafile": "sipos_2006_fig3_LiOH.csv",
        "experiment_samples": [
          {
            "sample_name": "Lithium Hydroxide",
            "sample_factors": [
              {
                "factor_type": "Measurement Condition",
                "unit_reference": "Molar",
                "csv_column_index": 0
              }
            ],
            "sample_species": [
              {
                "species_reference": "Li+",
                "stoichiometry": 1.0
              },
              {
                "species_reference": "OH-",
                "stoichiometry": 1.0
              }
            ]
          },
          {
            "sample_name": "Aluminate Solution",
            "sample_factors": [
              {
                "factor_type": "Measurement Condition",
                "decimal_value": 0.005,
                "unit_reference": "Molar"
              },
              {
                "factor_type": "Measurement",
                "unit_reference": "ppm",
                "reference_value": "27_Al",
                "csv_column_index": 1
              }
            ],
            "sample_species": [
              {
                "species_reference": "Al(III)",
                "stoichiometry": 1.0
              }
            ],
            "sample_sources": [
              {
                "source_name": "Aluminum Wire",
                "source_factors": [
                  {
                    "factor_type": "Material Property",
                    "decimal_value": 0.98,
                    "unit_reference": "Percent",
                    "reference_value": "Purity by Weight"
                  }
                ],
                "source_species": [
                  {
                    "species_reference": "Al(III)",
                    "stoichiometry": 1.0
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "experiment_name": "Sodium Hydroxide Assay",
        "experiment_datafile": "sipos_2006_fig3_NaOH.csv",
        "experiment_samples": [
          {
            "sample_name": "Sodium Hydroxide",
            "sample_factors": [
              {
                "factor_type": "Measurement Condition",
                "unit_reference": "Molar",
                "csv_column_index": 0
              }
            ],
            "sample_species": [
              {
                "species_reference": "Na+",
                "stoichiometry": 1.0
              },
              {
                "species_reference": "OH-",
                "stoichiometry": 1.0
              }
            ]
          },
          {
            "sample_name": "Aluminate Solution",
            "sample_factors": [
              {
                "factor_type": "Measurement Condition",
                "decimal_value": 0.005,
                "unit_reference": "Molar"
              },
              {
                "factor_type": "Measurement",
                "unit_reference": "ppm",
                "reference_value": "27_Al",
                "csv_column_index": 1
              }
            ],
            "sample_species": [
              {
                "species_reference": "Al(III)",
                "stoichiometry": 1.0
              }
            ],
            "sample_sources": [
              {
                "name": "Aluminum Wire",
                "source_factors": [
                  {
                    "factor_type": "Material Property",
                    "decimal_value": 0.98,
                    "unit_reference": "Percent",
                    "reference_value": "Purity by Weight"
                  }
                ],
                "source_species": [
                  {
                    "species_reference": "Al(III)",
                    "stoichiometry": 1.0
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "experiment_name": "Sodium Hydroxide v Aluminate Assay",
        "experiment_datafile": "sipos_2006_fig2.csv",
        "experiment_samples": [
          {
            "sample_name": "Sodium Hydroxide",
            "sample_factors": [
              {
                "factor_type": "Measurement Condition",
                "unit_reference": "Molar",
                "csv_column_index": 1
              }
            ],
            "sample_species": [
              {
                "species_reference": "Na+",
                "stoichiometry": 1.0
              },
              {
                "species_reference": "OH-",
                "stoichiometry": 1.0
              }
            ]
          },
          {
            "sample_name": "Aluminate Solution",
            "sample_factors": [
              {
                "factor_type": "Measurement Condition",
                "unit_reference": "Molar",
                "csv_column_index": 0
              },
              {
                "factor_type": "Measurement",
                "unit_reference": "ppm",
                "reference_value": "27_Al",
                "csv_column_index": 2
              }
            ],
            "sample_species": [
              {
                "species_reference": "Al(III)",
                "stoichiometry": 1.0
              }
            ]
          }
        ]
      }
    ]
  }
